# yml 파일 포맷의 version 설정
version: "3.9"

# 띄울 컨테이너 목록
services:
  # 순서상 database가 먼저 와야 함
  # mysql:
  #   image: mysql:8
  #   # 환경 설정 부분
  #   env_file:
  #     - ./.env
  #   container_name: gitodoc_db
  #   ports:
  #     - "3306:3306"
  #   # 가상 네트워크 연결
  #   networks:
  #     - gtd

  backend:
    # 환경 설정 부분
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - .:/backend
    # command : 컨테이너가 띄워질 때 실행하는 명령어 / 서버실행
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
      - 8000:8000
    # 가상 네트워크 연결
    # links:
    #   - mysql:mysql
    networks:
      - gtd
    # depends_on:
    #   - mysql
    expose:
      - 8000

networks:
  gtd:
    driver: bridge
