name: Django CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]
  
    steps:
    - uses: actions/checkout@v3
  
    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
    
    - name: Docker-Compose Down
      run: |
        if [ "$(docker ps -q -f name=container_name)" ]; then
          docker-compose -f docker-compose.dev.yml down
        fi
    
    - name: Docker-Compose Build
      run: |
        docker-compose -f docker-compose.dev.yml build
    
    - name: Docker-Compose Up
      run: |
        result=$(docker-compose -f docker-compose.dev.yml up -d --remove-orphans)  # 결과를 변수에 저장
        echo "$result"
        if [[ "$result" != *"Recreating backend ... done"* ]]; then  # 출력 결과가 "Recreating backend ... done"을 포함하지 않으면
          docker-compose -f docker-compose.dev.yml down  # Docker 컨테이너를 종료
          exit 1  # 실패 상태로 종료
        fi
