name: Django CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]
  
    steps:
    - uses: actions/checkout@v3
  
    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
    
    - name: Docker-Compose Build
      run: |
        docker-compose -f docker-compose.dev.yml build
    
    - name: Docker-Compose Up
      run: |
        docker-compose -f docker-compose.dev.yml up
